apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: campus-market
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: campus_user
  SPRING_DATASOURCE_PASSWORD: campus_pass
  JWT_SECRET: change-me-super-secret-key-please-replace-with-longer-string-123456
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin

