services:
  backend:
    environment:
      MINIO_ENDPOINT: http://host.docker.internal:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}

  minio: null
